spring:
  datasource:
    url: jdbc:h2:file:./plan-db
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev